"""add normalized tables

Revision ID: 49428a807577
Revises: 7364e076def2
Create Date: 2026-01-25 17:18:47.030611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49428a807577'
down_revision: Union[str, None] = '7364e076def2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracting_authority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('activity_type', sa.String(length=255), nullable=True),
    sa.Column('admin_unit_type', sa.String(length=100), nullable=True),
    sa.Column('admin_unit_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contracting_authority_name', 'contracting_authority', ['name'], unique=False)
    op.create_index(op.f('ix_contracting_authority_tax_number'), 'contracting_authority', ['tax_number'], unique=True)
    op.create_table('procurement_procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('subcategory', sa.String(length=500), nullable=True),
    sa.Column('has_lots', sa.Boolean(), nullable=True),
    sa.Column('is_auction_online', sa.Boolean(), nullable=True),
    sa.Column('is_master_agreement', sa.Boolean(), nullable=True),
    sa.Column('is_defense_and_security', sa.Boolean(), nullable=True),
    sa.Column('is_joint_procurement', sa.Boolean(), nullable=True),
    sa.Column('award_criterion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_procedure_number'), 'procurement_procedure', ['number'], unique=True)
    op.create_index('ix_procurement_procedure_type', 'procurement_procedure', ['type'], unique=False)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_foreign', sa.Boolean(), nullable=True),
    sa.Column('size_category', sa.String(length=100), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_name', 'supplier', ['name'], unique=False)
    op.create_index('ix_supplier_tax_name', 'supplier', ['tax_number', 'name'], unique=False)
    op.create_index(op.f('ix_supplier_tax_number'), 'supplier', ['tax_number'], unique=False)
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contracting_authority_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('lot_name', sa.String(length=500), nullable=True),
    sa.Column('main_cpv_code', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annual_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('monthly_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_date', sa.DateTime(), nullable=True),
    sa.Column('master_agreement_start_date', sa.DateTime(), nullable=True),
    sa.Column('master_agreement_end_date', sa.DateTime(), nullable=True),
    sa.Column('number_of_received_offers', sa.Integer(), nullable=True),
    sa.Column('number_of_acceptable_offers', sa.Integer(), nullable=True),
    sa.Column('lowest_acceptable_offer_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('highest_acceptable_offer_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('eu_funds_used', sa.Boolean(), nullable=True),
    sa.Column('completed_with_negotiation', sa.Boolean(), nullable=True),
    sa.Column('preferential_treatment_used', sa.Boolean(), nullable=True),
    sa.Column('legal_remedies_used', sa.Boolean(), nullable=True),
    sa.Column('is_contract_concluded', sa.Boolean(), nullable=True),
    sa.Column('allowed_subcontracting', sa.Boolean(), nullable=True),
    sa.Column('subcontracting_share', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('subcontracting_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('regulation_quote_name', sa.String(length=255), nullable=True),
    sa.Column('reasons_for_negotiated_procedure', sa.Text(), nullable=True),
    sa.Column('source_country', sa.String(length=10), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('raw_award_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contracting_authority_id'], ['contracting_authority.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procurement_procedure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_contract_date'), 'award', ['contract_date'], unique=False)
    op.create_index(op.f('ix_award_contracting_authority_id'), 'award', ['contracting_authority_id'], unique=False)
    op.create_index(op.f('ix_award_procedure_id'), 'award', ['procedure_id'], unique=False)
    op.create_index('ix_award_source', 'award', ['source_country', 'source_system'], unique=False)
    op.create_index('ix_award_value', 'award', ['value'], unique=False)
    op.create_table('award_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['award.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('award_id', 'supplier_id', name='uq_award_supplier')
    )
    op.create_index(op.f('ix_award_supplier_award_id'), 'award_supplier', ['award_id'], unique=False)
    op.create_index('ix_award_supplier_role', 'award_supplier', ['role'], unique=False)
    op.create_index(op.f('ix_award_supplier_supplier_id'), 'award_supplier', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_award_supplier_supplier_id'), table_name='award_supplier')
    op.drop_index('ix_award_supplier_role', table_name='award_supplier')
    op.drop_index(op.f('ix_award_supplier_award_id'), table_name='award_supplier')
    op.drop_table('award_supplier')
    op.drop_index('ix_award_value', table_name='award')
    op.drop_index('ix_award_source', table_name='award')
    op.drop_index(op.f('ix_award_procedure_id'), table_name='award')
    op.drop_index(op.f('ix_award_contracting_authority_id'), table_name='award')
    op.drop_index(op.f('ix_award_contract_date'), table_name='award')
    op.drop_table('award')
    op.drop_index(op.f('ix_supplier_tax_number'), table_name='supplier')
    op.drop_index('ix_supplier_tax_name', table_name='supplier')
    op.drop_index('ix_supplier_name', table_name='supplier')
    op.drop_table('supplier')
    op.drop_index('ix_procurement_procedure_type', table_name='procurement_procedure')
    op.drop_index(op.f('ix_procurement_procedure_number'), table_name='procurement_procedure')
    op.drop_table('procurement_procedure')
    op.drop_index(op.f('ix_contracting_authority_tax_number'), table_name='contracting_authority')
    op.drop_index('ix_contracting_authority_name', table_name='contracting_authority')
    op.drop_table('contracting_authority')
    # ### end Alembic commands ###
