"""create awards_raw table

Revision ID: 11515d2fc74a
Revises: 
Create Date: 2026-01-25 13:36:46.021013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11515d2fc74a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_country', sa.String(length=10), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('import_batch_id', sa.String(length=50), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('lot_name', sa.String(length=500), nullable=True),
    sa.Column('main_cpv_code', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annual_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('monthly_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_date', sa.DateTime(), nullable=True),
    sa.Column('master_agreement_start_date', sa.DateTime(), nullable=True),
    sa.Column('master_agreement_end_date', sa.DateTime(), nullable=True),
    sa.Column('contracting_authority_name', sa.String(length=500), nullable=True),
    sa.Column('contracting_authority_tax_number', sa.String(length=100), nullable=True),
    sa.Column('contracting_authority_city_name', sa.String(length=255), nullable=True),
    sa.Column('contracting_authority_type', sa.String(length=100), nullable=True),
    sa.Column('contracting_authority_activity_type_name', sa.String(length=255), nullable=True),
    sa.Column('contracting_authority_administrative_unit_type', sa.String(length=100), nullable=True),
    sa.Column('contracting_authority_administrative_unit_name', sa.String(length=255), nullable=True),
    sa.Column('procedure_name', sa.String(length=500), nullable=True),
    sa.Column('procedure_number', sa.String(length=100), nullable=True),
    sa.Column('procedure_type', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('contract_category_name', sa.String(length=500), nullable=True),
    sa.Column('contract_subcategory_name', sa.String(length=500), nullable=True),
    sa.Column('has_lots', sa.Boolean(), nullable=True),
    sa.Column('is_auction_online', sa.Boolean(), nullable=True),
    sa.Column('is_master_agreement', sa.Boolean(), nullable=True),
    sa.Column('is_defense_and_security', sa.Boolean(), nullable=True),
    sa.Column('is_joint_procurement', sa.Boolean(), nullable=True),
    sa.Column('is_on_behalf_procurement', sa.Boolean(), nullable=True),
    sa.Column('completed_with_negotiation', sa.Boolean(), nullable=True),
    sa.Column('preferential_treatment_used', sa.Boolean(), nullable=True),
    sa.Column('eu_funds_used', sa.Boolean(), nullable=True),
    sa.Column('legal_remedies_used', sa.Boolean(), nullable=True),
    sa.Column('is_contract_concluded', sa.Boolean(), nullable=True),
    sa.Column('allowed_subcontracting', sa.Boolean(), nullable=True),
    sa.Column('award_criterion', sa.String(length=500), nullable=True),
    sa.Column('number_of_received_offers', sa.Integer(), nullable=True),
    sa.Column('number_of_acceptable_offers', sa.Integer(), nullable=True),
    sa.Column('lowest_acceptable_offer_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('highest_acceptable_offer_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('subcontracting_share', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('subcontracting_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('regulation_quote_name', sa.String(length=255), nullable=True),
    sa.Column('reasons_for_negotiated_procedure', sa.Text(), nullable=True),
    sa.Column('supplier_name', sa.String(length=500), nullable=True),
    sa.Column('supplier_tax_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_is_foreign', sa.Boolean(), nullable=True),
    sa.Column('supplier_country', sa.String(length=100), nullable=True),
    sa.Column('supplier_size_category', sa.String(length=100), nullable=True),
    sa.Column('supplier_is_registered', sa.Boolean(), nullable=True),
    sa.Column('other_suppliers_in_group', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('awards_raw')
    # ### end Alembic commands ###
